name: Test & Lint

on: [push, pull_request]

jobs:
  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - uses: mydea/actions-ember-testing@v2
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test:ember
      - name: Lint
        run: |
          yarn lint:js
          yarn lint:hbs
  test-matrix:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        # Keep this in sync with config/ember-try.js
        ember:
          [
            ember-3.13,
            ember-lts-3.16,
            ember-release,
            ember-beta,
            ember-canary,
            ember-default-with-jquery,
            ember-classic,
          ]

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - uses: mydea/actions-ember-testing@v2
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test:one ${{ matrix.ember }}
